const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn } = require('child_process');

const SEARCH_TIMEOUT_MS = 15000;
const METADATA_TIMEOUT_MS = 18000;

const ytDlpPackageRoot = () => {
  const entryPath = require.resolve('@distube/yt-dlp');
  return path.resolve(path.dirname(entryPath), '..');
};

const packagedYtDlpPath = () => {
  const fileName = process.platform === 'win32' ? 'yt-dlp.exe' : 'yt-dlp';
  return path.join(ytDlpPackageRoot(), 'bin', fileName);
};

const resolveYtDlpPath = () => {
  if (process.env.YTDLP_PATH) return process.env.YTDLP_PATH;
  const packaged = packagedYtDlpPath();
  if (fs.existsSync(packaged)) return packaged;
  return 'yt-dlp';
};

let ensurePromise = null;
let cookieFilePath = null;

const normalizeCookieText = (value) => String(value || '').replace(/\r\n/g, '\n').trim();

const boolToCookieFlag = (value) => (value ? 'TRUE' : 'FALSE');

const domainFromCookie = (cookie) => {
  const rawDomain = String(cookie?.domain || cookie?.host || '.youtube.com').trim();
  if (!rawDomain) return '.youtube.com';
  return rawDomain.startsWith('.') ? rawDomain : `.${rawDomain}`;
};

const normalizeJsonCookie = (cookie) => {
  const name = String(cookie?.name || '').trim();
  const value = String(cookie?.value || '');
  if (!name) return null;

  const domain = domainFromCookie(cookie);
  const includeSubdomains = domain.startsWith('.');
  const pathValue = String(cookie?.path || '/');
  const secure = Boolean(cookie?.secure);
  const expiresRaw = cookie?.expirationDate ?? cookie?.expires ?? cookie?.expiry ?? 0;
  const expires = Number.isFinite(Number(expiresRaw)) ? Math.trunc(Number(expiresRaw)) : 0;

  return [
    domain,
    boolToCookieFlag(includeSubdomains),
    pathValue || '/',
    boolToCookieFlag(secure),
    expires > 0 ? expires : 0,
    name,
    value,
  ].join('\t');
};

const collectJsonCookies = (value, out = []) => {
  if (!value || typeof value !== 'object') return out;
  if (Array.isArray(value)) {
    value.forEach((item) => collectJsonCookies(item, out));
    return out;
  }

  if (
    Object.prototype.hasOwnProperty.call(value, 'name')
    && Object.prototype.hasOwnProperty.call(value, 'value')
    && (value.domain || value.host || value.url || value.path)
  ) {
    out.push(value);
    return out;
  }

  Object.values(value).forEach((item) => collectJsonCookies(item, out));
  return out;
};

const cookiesJsonToNetscape = (cookieText) => {
  let parsed;
  try {
    parsed = JSON.parse(cookieText);
  } catch {
    return null;
  }

  const list = collectJsonCookies(parsed);
  const lines = list.map(normalizeJsonCookie).filter(Boolean);
  if (lines.length === 0) return null;

  return [
    '# Netscape HTTP Cookie File',
    '# Generated by Aether backend from JSON cookie export.',
    ...lines,
  ].join('\n');
};

const prepareCookieText = (cookieText) => {
  const normalized = normalizeCookieText(cookieText);
  if (!normalized) return '';
  if (normalized.startsWith('# Netscape HTTP Cookie File') || normalized.includes('\t')) {
    return normalized;
  }
  const converted = cookiesJsonToNetscape(normalized);
  if (converted) {
    console.log('[Aether API] converted JSON YouTube cookies to Netscape format');
    return converted;
  }
  if (normalized.startsWith('{') || normalized.startsWith('[')) {
    console.warn('[Aether API] YouTube cookies env var is JSON, but no cookie entries were found; ignoring it');
    return '';
  }
  console.warn('[Aether API] YouTube cookies env var is present, but did not look like Netscape cookies');
  return normalized;
};

const resolveCookieFilePath = () => {
  if (cookieFilePath) return cookieFilePath;
  if (process.env.YOUTUBE_COOKIES_PATH && fs.existsSync(process.env.YOUTUBE_COOKIES_PATH)) {
    cookieFilePath = process.env.YOUTUBE_COOKIES_PATH;
    return cookieFilePath;
  }

  const rawCookieText = process.env.YOUTUBE_COOKIES_BASE64
    ? Buffer.from(process.env.YOUTUBE_COOKIES_BASE64, 'base64').toString('utf8')
    : process.env.YOUTUBE_COOKIES;
  const cookieText = prepareCookieText(rawCookieText);
  if (!cookieText) return null;

  cookieFilePath = path.join(os.tmpdir(), 'aether-youtube-cookies.txt');
  fs.writeFileSync(cookieFilePath, `${cookieText}\n`, { mode: 0o600 });
  return cookieFilePath;
};

const getCookieArgs = () => {
  const cookiesPath = resolveCookieFilePath();
  return cookiesPath ? ['--cookies', cookiesPath] : [];
};

const ensureYtDlp = async () => {
  if (ensurePromise) return ensurePromise;
  ensurePromise = (async () => {
    const packaged = packagedYtDlpPath();
    if (process.env.YTDLP_PATH || fs.existsSync(packaged)) return resolveYtDlpPath();

    try {
      const ytdlp = require('@distube/yt-dlp');
      if (typeof ytdlp.download === 'function') {
        await ytdlp.download();
      }
    } catch (error) {
      console.warn(`[Aether API] yt-dlp download failed: ${error.message}`);
    }

    return resolveYtDlpPath();
  })();
  return ensurePromise;
};

const runYtDlpLines = async (args, timeoutMs) => {
  const ytdlpPath = await ensureYtDlp();

  return new Promise((resolve, reject) => {
    const child = spawn(ytdlpPath, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    let settled = false;

    const done = (error, value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (error) reject(error);
      else resolve(value);
    };

    const timer = setTimeout(() => {
      try { child.kill('SIGKILL'); } catch {}
      done(new Error(`yt-dlp timed out after ${timeoutMs}ms`));
    }, timeoutMs);

    child.stdout.on('data', (chunk) => { stdout += chunk.toString(); });
    child.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
    child.on('error', (error) => done(error));
    child.on('close', (code) => {
      if (code !== 0) {
        done(new Error(stderr.trim() || `yt-dlp exited with code ${code}`));
        return;
      }
      done(null, stdout);
    });
  });
};

const normalizeTrack = (data) => {
  const id = data?.id ? String(data.id) : '';
  if (!id || !data?.title) return null;
  const url = data.webpage_url || data.original_url || data.url || `https://www.youtube.com/watch?v=${id}`;
  const durationMs = Math.max(0, Math.floor(Number(data.duration) || 0) * 1000);
  return {
    id,
    youtubeId: id,
    title: String(data.title || 'Unknown track'),
    author: String(data.uploader || data.channel || data.artist || 'Unknown Artist'),
    duration: durationMs,
    totalDurationMs: durationMs,
    url,
    actualUrl: url,
    thumbnail: data.thumbnail || data.thumbnails?.[0]?.url || '',
  };
};

const searchTracks = async (query) => {
  const q = String(query || '').trim();
  if (!q) return [];

  let stdout = '';
  try {
    stdout = await runYtDlpLines([
      `ytsearch20:${q}`,
      ...getCookieArgs(),
      '--dump-json',
      '--flat-playlist',
      '--no-check-certificates',
      '--no-warnings',
      '--skip-download',
    ], SEARCH_TIMEOUT_MS);
  } catch (error) {
    console.warn(`[Aether API] search failed for "${q.slice(0, 80)}": ${error.message}`);
    return [];
  }

  return stdout
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      try { return normalizeTrack(JSON.parse(line)); }
      catch { return null; }
    })
    .filter(Boolean);
};

const getMetadata = async (url) => {
  const target = String(url || '').trim();
  if (!target) return null;

  let stdout = '';
  try {
    stdout = await runYtDlpLines([
      target,
      ...getCookieArgs(),
      '--dump-json',
      '--no-check-certificates',
      '--no-warnings',
      '--skip-download',
    ], METADATA_TIMEOUT_MS);
  } catch (error) {
    console.warn(`[Aether API] metadata failed for "${target.slice(0, 120)}": ${error.message}`);
    return null;
  }

  return normalizeTrack(JSON.parse(stdout));
};

module.exports = {
  ensureYtDlp,
  getCookieArgs,
  getMetadata,
  searchTracks,
};
